### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by ThomasMahon** [gtalarico/ironpython-stubs#11]
The documentation for both Atom and Sublime is extremely poor and is insufficient to successfully set up either editor. 

Can you either update the documentation so time isn't wasted second-guessing what needs to be done (given up on both, and that was before I even got to the stubs!) or provide links to instructions online that provide adequate set-up instructions for these text editors.

**Comment by ThomasMahon** [comment]
The problem was ordinary Python has to be installed - can you ensure this step is highlighted in your documentation (and thanks for the stubs repository - its greatly appreciated)

**Comment by gtalarico** [comment]
I don't it's fair for you to say the documentation is "extremely poor and is insufficient".
There are 3 Wiki pages for individual editors with step by step, screenshots and gifs.

The documentation on how to configure each autocomplete engine is provided here mostly out of courtesy, as the setup of standard python autocomplete is outside the scope of this project.

Both pages explicitly stated you should have standard python autocompletion working before you attempt to add the stubs.

It's also rude and completely inappropriate to use this tone on an open source project created and maintained one's free time and will. If you are having issues you are always welcome to ask for help or clarification, but you should reconsider your approach.
