### ISSUE TITLE
Add instructions for Vim

### ISSUE THREAD

**Issue by tetov** [gtalarico/ironpython-stubs#14]
I wrote up instructions for using ironpython-stubs with Vim on my [blog](https://tetov.se/autocompletion-for-rhino-grasshopper-python-scripts-in-vim/) and then reformatted it to fit with this repo's wiki. You can find the .md file [here](https://gist.github.com/tetov/d4122bd92ecfdce4bc28545def41f126), GitHub doesn't allow pull requests to wikis..

~~If this change is accepted I'll make some gifs to add to the page.~~

Edit: I added some Asciinema videos to the linked gist.

**Comment by gtalarico** [comment]
Hi - thanks for the write up.
I have added you as a collaborator - Would you be willing to make the changes yourself? 
Feel free to add vim instructions or anything else you see fit. 
You should include a link to your article as well.

**Comment by tetov** [comment]
No, thank you!

I have added the the suggested changes.
