### ISSUE TITLE
Can't create the stubs in PyCharm's 

### ISSUE THREAD

**Issue by chuong9x** [gtalarico/ironpython-stubs#20]
Hello ! 
Im a user Pycham's,i want download link create stubs but it not found, you can update it help me, thanks you ! 
Error link described :
https://github.com/JetBrains/intellij-community/blob/master/python/helpers/generator3.py

**Comment by gtalarico** [comment]
This repo uses a tool that ships with PyCharm to create the stubs.
If you use pycharm you shouldn't need to use it.
