### ISSUE TITLE
Intellisense does not work for "unknown" elements.

### ISSUE THREAD

**Issue by jannisle** [gtalarico/ironpython-stubs#24]
Hi, 
thanks for providing this great tool :) I´m very pleased :)

But I run into a little problem with the intellisense. When pyCharm does not know which type my object has, it does not use intellisense and has no option to autocomplete.

I can put in if isinstance(element,type): and pyCharm shows intellisense now.
![image](https://user-images.githubusercontent.com/49270199/100737660-bc4a4780-33d4-11eb-8374-fd599cf99d48.png)

If I don´t, it doesn´t:
![image](https://user-images.githubusercontent.com/49270199/100737507-902ec680-33d4-11eb-8aba-e61dd6e80f8c.png)

Is there any solution / workaround to this problem or am I doing something completely wrong? Casting an object with view = (DB.Elemt)view does not work.

Kind regards :)

**Comment by PavelAltynnikov** [comment]
Hi @jannisle.
I don't know if this will work in pyCharm, but in the vs code you can designate the type like this
![image](https://user-images.githubusercontent.com/45833327/144752983-7556b3d4-0819-4e43-89b0-2ab7ace32966.png)

**Comment by jannisle** [comment]
Works perfectly :) Thank you :)
