### ISSUE TITLE
How to split a cable and conduits with dynamo. Any idea?

### ISSUE THREAD

**Issue by lbhardwa** [gtalarico/ironpython-stubs#27]

**Comment by gtalarico** [comment]
@lbhardwa I am not able to help with questions like this in this repo.
This issue board is only for issues, bugs, and questions about the ironpython stubs.

A better place for your question would  be https://forum.dynamobim.com/ or  https://forums.autodesk.com/t5/revit-api-forum/bd-p/160

I would also suggest you take a look at the pages below for suggestions on how to ask questions/help online:
* https://stackoverflow.com/help/how-to-ask
* https://forum.dynamobim.com/t/how-to-get-help-on-the-dynamo-forums/4677
