### ISSUE TITLE
IronPython stubs for Robot

### ISSUE THREAD

**Issue by erfajo** [gtalarico/ironpython-stubs#4]
Are you planning to do stubs on Robot?
if not, could you give some hints how to make stubs then? ...and would you be interested in adding it to you package if I then do the job?

**Comment by gtalarico** [comment]
I haven't used it before, but we can definitely add it. Where can I get the dll from? Can you post a link to it?

**Comment by erfajo** [comment]
I have tried to find something about the API, but it is not so well structured as the Revit API... try to see if this helps
https://www.dropbox.com/s/aegp215uokrsy5i/SDK.zip?dl=0
https://www.dropbox.com/s/zfdhfpsvds8jc22/Robot.zip?dl=0

**Comment by gtalarico** [comment]
Wont' fix for now.
I am working on making the project easier to use by others.
Once I get there, people will be able to contribute by parsing their own libraries.
